### ISSUE TITLE
Can't change tabs when in terminal

### ISSUE THREAD

**Issue by barreyra** [macvim-dev/macvim#1045]
When entering a terminal, I can no longer change tabs using Cmd-{}, not create a new one using Cmd-T, presumably because these keys get passed on to the terminal.

**Comment by eirnym** [comment]
If you're talking about Apple's `Terminal.app`, it doesn't support passing Cmd key to apps. Some other terminal apps has limited support for this feature

**Comment by barreyra** [comment]
I'm talking about the MacVim GUI. I can use those keys normally to switch between tabs in other buffers, but if the current selected buffer is a `:terminal`, it doesn't work.

**Comment by eirnym** [comment]
As far as I understand, Vim captures the input and then sends it to the terminal, which is not the same as you process a key directly. Also Vim's terminal emulator is not perfect enough to be compared to Xterm, for example.

**Comment by barreyra** [comment]
Aha, I figured out my own issue. The terminal has its own set of key-bindings. The following adds the basic tab navigation commands:

    tmap <D-t> <C-W>:tabnew<CR>
    tmap <D-}> <C-W>:tabn<CR>
    tmap <D-{> <C-W>:tabp<CR>

Now I need to figure out where these bindings are set in MacVim, then I'll send a merge request.

**Comment by ychin** [comment]
I think the issue is that the menu entries are not properly mapped. This will be fixed next release to have the tab menu items properly mapped in terminal mode.

**Comment by ychin** [comment]
This is now fixed. @barreyra feel free to remove your own mappings once the new version (164) is out soon. MacVim will do the right thing.

**Comment by barreyra** [comment]
Thank you, it works great. Cmd-w and Cmd-b are still missing, I'll post a patch if no one else does.

**Comment by ychin** [comment]
I'm not sure if Cmd-W would work. It's mapped to `:conf q` which I don't think works inside terminal mode. I could see Cmd-B though.
