### ISSUE TITLE
long standing 'gx' bug fixed upstream. Please, rerelease MacVim

### ISSUE THREAD

**Issue by slonik-az** [macvim-dev/macvim#1094]
Vim upstream just updated netrw to version v170 
https://github.com/vim/vim/commit/1d59aa1fdfb191d9872ff87eb94652acd374b293#diff-3abb9629535900f0c07a312231e18483R4

It suppose to fix long standing bug of broken `gx` key binding (netrw), reported in 
https://github.com/vim/vim/issues/4738

Please, rerelease  MacVim

Thanks,
--Leo

**Comment by ychin** [comment]
It's going to be released in a couple days, but I'll make sure this change is included.

**Comment by ychin** [comment]
Actually I don't think this is fixed? Tried it on latest Vim and doesn't seem like it to me. Did anyone actually confirm this?

Tbh at this point I think it's just easiest if someone makes a plugin just to do this than to rely on netrw. Just my 2c.

**Comment by slonik-az** [comment]
@k-takata claims it is fixed in netrw v170 and he closed the corresponding  issue https://github.com/vim/vim/issues/4738 based on this assertion.

**Comment by xdhmoore** [comment]
It does not work for me after upgrading to MacVim 8.2.1719. In a buffer with the following:

```
blah lgah https://google.com asdfas  asdf
dog fish cat lion
```
If I press `gx` over the url it closes the buffer, and opens an unrelated file from my history, then displays a netrw error on top of line 2 of the new buffer. I've reproduced this 3 times or so:

<img width="1046" alt="Screen Shot 2020-09-21 at 2 16 11 PM" src="https://user-images.githubusercontent.com/5142129/93822468-21373380-fc15-11ea-85be-2891a4d234ee.png">

If I start over and add a trailing slash to the above url (https://google.com/), hitting `gx` opens a browser window with a local copy of the html file, as well as closing the current buffer and also opening an unrelated file from my history in the current MacVim window.

**Comment by ychin** [comment]
Since we have determined that upstream didn't fix this, I'm just going to close this as dup of #925, which is in the backlog already.
